---
    ## Disable password authentication
    - name: "Set ssh port number to {{ rhel_ssh_port }}"
      lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Port\s"
              line="Port {{ rhel_ssh_port }}"
              state=present
      become: yes
      notify: restart sshd
      when: ssh_enforce_port_number


    ## This step will fail if firewalld isn't running. Since this won't cause us a problem we just skip on error
    - name: "Open firewalld port number to {{ rhel_ssh_port }}"
      firewalld:
        port: "{{ rhel_ssh_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      become: yes
      when: ssh_open_firewalld_port
      ignore_errors: yes


    - name: "Allow SSH password authentication ? : {{ ssh_allow_password_authentication }} "
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^.*PasswordAuthentication.*"
                  line="PasswordAuthentication {{ ssh_allow_password_authentication }}"
                  state=present
      become: yes
      notify: restart sshd
      when: ssh_enforce_disable_password_authentication

    - name: "Allow root SSH access ? : {{ ssh_permit_root_login }}"
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^.*PermitRootLogin.*$"
                  line="PermitRootLogin {{ ssh_permit_root_login }}"
                  state=present
      become: yes
      notify: restart sshd
      when: ssh_enforce_disable_root_access


    - name: "Allow ssh tunneling ? : {{ ssh_permit_tunnel }}"
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^.*PermitTunnel.*$"
                  line="PermitTunnel {{ ssh_permit_tunnel }}"
                  state=present
      become: yes
      notify: restart sshd
      when: ssh_enforce_tunneling_rules



